name: formularze
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_signaturepad: ^29.2.10
  intl: ^0.18.0
  uuid: ^3.0.7
  pdf: ^3.10.0
  printing: ^5.11.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  email_validator: ^2.1.17
  http: ^1.5.0
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  fonts:
    - family: TimesNewRoman
      fonts:
        - asset: assets/fonts/times.ttf
        - asset: assets/fonts/times-bold.ttf
  assets:
    - assets/images/pl.png
    - assets/images/en.png
    - assets/images/logo.png
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
